In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [3]:
url = "http://www.hubertiming.com/results/2017GPTR10K"
html = urlopen(url)

In [4]:
soup = BeautifulSoup(html, 'lxml')
type(soup)

bs4.BeautifulSoup

In [6]:
# Print out the text
text = soup.get_text()
print(soup.text)

Race results for the 2017 Intel Great Place to Run \ Urban Clash Games!





















 2017 Intel Great Place to Run 10K \ Urban Clash Games
 Hillsboro Stadium, Hillsboro, OR
 June 2nd, 2017








 Email
                        timing@hubertiming.com with results questions. Please include your bib number if you have it.









Huber Timing Home





10K:


Finishers:
577


Male:
414


Female:
163









 5K Individual
 5K Team
 10K Individual
 10K Team
 Summary




Indvidual Results



10K Results



Search:

Search
Division:

Men
Women
Non-Binary
Masters Men
Masters Women
Masters Non-Binary

F 18-25
F 26-35
F 36-45
F 46-55
F Under 18
M 18-25
M 26-35
M 36-45
M 46-55
M 55+
M Under 18
 Team:

Unattached
COLUMBIA TEAM A
COLUMBIA TEAM B
COLUMBIA TEAM C
COLUMBIA TEAM D
COLUMBIA TEAM E
DTNA1
DTNA2
DTNA3
FXG1
INTEL TEAM A
INTEL TEAM B
INTEL TEAM C
INTEL TEAM D
INTEL TEAM E
INTEL TEAM F
INTEL TEAM G
INTEL TEAM H
INTEL TEAM I
INTEL TEAM J
INTEL TEAM K
INTEL TEAM L
INTEL TEAM M
INTEL TEAM N
 Filter




Place
Bib
Name
Gender
City
State
Time
Gun Time
Team




1
814


                    JARED WILSON


M
TIGARD
OR
36:21
36:24



2
573


                    NATHAN A SUSTERSIC


M
PORTLAND
OR
36:42
36:45


                            INTEL TEAM F



3
687


                    FRANCISCO MAYA


M
PORTLAND
OR
37:44
37:48



4
623


                    PAUL MORROW


M
BEAVERTON
OR
38:34
38:37



5
569


                    DEREK G OSBORNE


M
HILLSBORO
OR
39:21
39:24


                            INTEL TEAM F



6
642


                    JONATHON TRAN


M
PORTLAND
OR
39:49
39:55



7
144


                    GEORGE TOTONCHY


M
PORTLAND
OR
40:04
40:17



8
395


                    BENJAMIN C CHAFFIN


M
PORTLAND
OR
40:05
40:09



9
7


                    BRANDON THOMAS


M


40:17
40:24


                            COLUMBIA TEAM B



10
3


                    ERIK BJORNSTAD


M


40:21
40:25


                            COLUMBIA TEAM A



11
68


                    WITALI SPULING


M
PORTLAND
OR
40:28
40:40


                            DTNA1



12
788


                    ANDY WEDAM


M
PORTLAND
OR
40:36
40:42


                            DTNA2



13
729


                    MICHAEL P GEORGE


M
PORTLAND
OR
40:43
40:50



14
151


                    ETHAN JORDAN


M
PORTLAND
OR
41:01
41:13



15
758


                    FLAVIO GRIGGIO


M
PORTLAND
OR
41:19
41:24



16
868


                    WILLIAM BARRY


M
BEAVERTON
OR
41:43
41:49


                            INTEL TEAM K



17
2


                    JIM DROZDOWSKI


M


41:59
42:02


                            COLUMBIA TEAM A



18
362


                    BRITON BARKER


M
HILLSBORO
OR
42:23
42:28



19
755


                    NEILANJAN DUTTA


M
HILLSBORO
OR
42:29
42:34



20
543


                    KENNETH KLOTZ


M
EUGENE
OR
42:35
42:48



21
401


                    EDDIE J FRIE


M
HILLSBORO
OR
42:36
42:52


                            INTEL TEAM K



22
155


                    JARED PAGER


M
PORTLAND
OR
42:37
42:58



23
781


                    DAVID HERRON


M
PORTLAND
OR
42:56
43:04


                            FXG1



24
468


                    TIMOTHY WESLEY


M
NOT SPECIFIED
OR
43:26
43:36



25
882


                    MONROE SULLIVAN


M
PORTLAND
OR
43:27
43:30



26
236


                    VINCENT OLSEN


M
BOISE
ID
43:40
43:43



27
742


                    LEONARD NEIBERG


M
PORTLAND
OR
43:42
44:01



28
344


                    BENJAMIN JANN


M
HILLSBORO
OR
43:43
43:52



29
732


                    ANDREW HUNTER


M
BEAVERTON
OR
43:46
43:51



30
253


                    SAMANTHA BAGLEY


F
HILLSBORO
OR
43:46
43:53


                            INTEL TEAM K



31
674


                    TAYSEER MAHDI


F
HILLSBORO
OR
43:47
43:52



32
761


                    CHEN-GUAN LEE


M
PORTLAND
OR
43:47
43:52



33
560


                    LEONARDO PEREZ


M
HILLSBORO
OR
44:04
44:10



34
789


                    VASILIOS TSIRIMIAGOS


M
PORTLAND
OR
44:05
44:12


                            DTNA2



35
807


                    DAN CAMPBELL


M
HILLSBORO
OR
44:06
44:18



36
646


                    JANELLE M KLASER


F
PORTLAND
OR
44:07
44:17



37
740


                    YOSHIYASU YAMAKAWA


M
PORTLAND
OR
44:23
44:29



38
874


                    JONATHAN M MARTIN


M
PORTLAND
OR
44:38
45:09



39
361


                    RICHARD FLORES


M
PORTLAND
OR
44:41
45:10



40
710


                    DAVID W GAIBLER


M
PORTLAND
OR
44:42
44:46



41
791


                    ANDRE RAUCH


M
PORTLAND
OR
44:48
45:01


                            DTNA2



42
867


                    JOSHUA FEDDERLY


M
BEAVERTON
OR
45:03
45:46



43
142


                    TONDERAI NEMARUNDWE


M
BEAVERTON
OR
45:05
45:09



44
787


                    JONATHAN PARSONS


M
PORTLAND
OR
45:10
45:22


                            DTNA2



45
673


                    PIETER ROWLETTE


M
PORTLAND
OR
45:11
45:30



46
746


                    RAMON CALDERER


M
PORTLAND
OR
45:11
45:18



47
770


                    JONATHAN M HATFIELD


M
PORTLAND
OR
45:13
45:35



48
622


                    DAVID N GOLDSTEIN


M
BEAVERTON
OR
45:14
45:32



49
625


                    GREGORY M RUTTER


M
HILLSBORO
OR
45:15
45:26



50
635


                    STEFAN MEISTER


M
NOT SPECIFIED
OR
45:17
45:24



51
765


                    MATT TRAVERSO


M
HILLSBORO
OR
45:27
45:53



52
438


                    KEN W GILDERSLEEVE


M
PORTLAND
OR
45:28
45:34



53
582


                    ANDREW L HERTEL


M
HILLSBORO
OR
45:29
45:42


                            INTEL TEAM A



54
696


                    CHRISTOPHER L QUAM


M
PORTLAND
OR
45:36
46:31



55
580


                    SICELO MASANGO


M
HILLSBORO
OR
45:36
46:17



56
558


                    CHAD MUSZYNSKI


M
HILLSBORO
OR
45:40
45:59



57
47


                    FUMIE K WEIBY


F
PORTLAND
OR
45:40
46:02



58
303


                    AURELIEN T MOZIPO


M
BEAVERTON
OR
45:49
45:57



59
271


                    KYLE H AMBERT


M
TIGARD
OR
45:55
46:05


                            INTEL TEAM I



60
39


                    BRANDON LADICK


M
PORTLAND
OR
46:02
46:07



61
223


                    ADRIAN POP


M
WEST LINN
OR
46:13
46:16



62
671


                    AARON G JOHNSON


M
HILLSBORO
OR
46:20
46:39



63
574


                    MATTHEW BROWN


M
ALOHA
OR
46:23
46:28



64
349


                    EDMONDO MAZZULLI


M
HILLSBORO
OR
46:26
46:33


                            INTEL TEAM B



65
423


                    MILES F SCHWARTZ


M
PORTLAND
OR
46:33
46:58



66
783


                    LEO SOTO


M
PORTLAND
OR
46:35
48:01


                            FXG1



67
13


                    NICHOLAS FISCHER


M


46:41
47:02


                            COLUMBIA TEAM D



68
327


                    CHASE MCCLOSKEY


M
HILLSBORO
OR
46:42
46:53



69
67


                    INGA ANDREYEVA


F
PORTLAND
OR
46:45
46:57


                            DTNA1



70
283


                    THOR SEWELL


M
BEAVERTON
OR
46:46
47:06



71
153


                    TODD HARRIS


M
PORTLAND
OR
46:47
47:00



72
606


                    ABHIRAM MURALIDHAR


M
HILLSBORO
OR
46:49
47:49



73
841


                    JACK E LUBY


M
PORTLAND
OR
46:49
46:56



74
49


                    AURORE LARIVEN


F
PORTLAND
CA
46:52
47:09



75
704


                    RYAN MANIS


M
BEAVERTON
OR
46:55
48:54



76
393


                    LUCAS M JENISON


M
BEAVERTON
OR
46:56
47:32



77
858


                    RICHARD M STEGER


M
BEAVERTON
OR
47:00
47:21



78
536


                    GERMAN VILLALOBOS


M
HILLSBORO
OR
47:02
47:10



79
811


                    MICHAEL BEALE


M
HILLSBORO
OR
47:05
47:37



80
6


                    RANIER EVANS


M


47:05
47:13


                            COLUMBIA TEAM B



81
893


                    BRAD STEFANELLI


M
PORTLAND
OR
47:08
47:41



82
656


                    MALLORY TYLER


F
PORTLAND
OR
47:09
47:30



83
697


                    ANIRUDH MODI


M
PORTLAND
OR
47:27
48:28



84
256


                    BRAD CHADDICK


M
PORTLAND
OR
47:29
47:45



85
227


                    LYNNETTE NGUYEN


F
PORTLAND
OR
47:31
47:36



86
764


                    REBECCA JENSEN


F
HILLSBORO
OR
47:35
47:59



87
333


                    JIMMY E CASSIS


M
HILLSBORO
OR
47:42
47:55



88
17


                    BENJAMIN HODGDON


M


47:45
48:12


                            COLUMBIA TEAM D



89
230


                    JONATHAN THACH


M
HILLSBORO
OR
47:49
48:01



90
548


                    DOUGLAS GRESHAM


M
PORTLAND
OR
47:50
48:03



91
862


                    CARLOS M VIVAS


M
PORTLAND
OR
47:55
48:09



92
347


                    TEAL HAND


M
OTHER
OR
47:56
48:09


                            INTEL TEAM D



93
359


                    AI SSA CHAI


F
PORTLAND
OR
47:56
48:09



94
31


                    SHAHAR TSAMERET


F
PORTLAND
OR
47:58
48:06



95
715


                    SHAOPENG WANG


M
HILLSBORO
OR
47:59
49:03



96
323


                    CONNOR SMITH


M
HILLSBORO
OR
48:09
48:20



97
415


                    CHRISTOPHER MOZAK


M
PORTLAND
OR
48:13
48:27



98
435


                    TODD BAIRD


M
BEAVERTON
OR
48:18
49:06



99
541


                    WENDY HEUSSNER


F
PORTLAND
OR
48:18
48:56



100
538


                    ASSAF SHAIM


M
HILLSBORO
OR
48:20
48:40



101
62


                    MICHAEL E TURK


M
HILLSBORO
OR
48:21
48:58



102
852


                    CHRISTOPHER M ROMAN


M
HILLSBORO
OR
48:29
49:03



103
601


                    ILAN TSAMERET


M
PORTLAND
OR
48:30
48:38



104
820


                    TRAVIS FURRER


M
OTHER
OR
48:37
49:36



105
587


                    BRIAN WIESENAUER


M
PORTLAND
OR
48:38
48:54



106
591


                    ERIN F WIESENAUER


F
PORTLAND
OR
48:39
48:56


                            INTEL TEAM N



107
849


                    PAUL H HONEYMAN-COLVIN


M
PORTLAND
OR
48:40
49:14



108
458


                    SATOSHI SUZUKI


M
HILLSBORO
OR
48:42
49:12



109
728


                    JORGE MUNOZ


M
BEAVERTON
OR
48:43
49:15



110
572


                    JUN TAKEI


M
PORTLAND
OR
48:44
49:05


                            INTEL TEAM B



111
461


                    REAGAN LOPEZ


M
HILLSBORO
OR
48:49
48:53


                            INTEL TEAM A



112
880


                    STEVEN R CECH


M
PORTLAND
OR
48:56
49:54



113
126


                    BENJAMIN R PORTER


M
HILLSBORO
OR
49:03
49:22


                            INTEL TEAM D



114
339


                    BEN BORGSTEDE


M
HILLSBORO
OR
49:09
50:01



115
270


                    KISHOR KHARBAS


M
HILLSBORO
OR
49:12
49:37


                            INTEL TEAM E



116
752


                    TERENCE LEE


M
PORTLAND
OR
49:18
49:26



117
660


                    OCTAVIO RAMOS


M
PORTLAND
OR
49:23
49:29



118
255


                    MARK SAVOY


M
HILLSBORO
OR
49:26
49:43



119
373


                    TONY SALAZAR


M
BEAVERTON
OR
49:30
50:03



120
42


                    MEGAN M GOODSON


F
PORTLAND
OR
49:32
49:52


                            INTEL TEAM A



121
331


                    VIVEKANANTHAN SANJEEPAN


M
HILLSBORO
OR
49:35
50:33



122
550


                    TREY GUNNELL


M
SALT LAKE CITY
UT
49:42
49:57



123
298


                    BENJAMIN BRADEA


M
HILLSBORO
OR
49:44
49:45



124
449


                    RAHULDEVA GHOSH


M
PORTLAND
OR
49:44
50:04



125
676


                    TSUAN-CHUNG CHANG


M
PORTLAND
OR
49:51
50:50



126
855


                    RODNEY B STEWART


M
TIGARD
OR
49:54
50:34



127
683


                    MYRON LEE


M
BEAVERTON
OR
49:58
51:22



128
798


                    JEFF BENDER


M
BEAVERTON
OR
50:07
51:29



129
711


                    ADAM J SCHAFER


M
PORTLAND
OR
50:12
51:05



130
598


                    DRAGOS SEGHETE


M
PORTLAND
OR
50:15
51:29



131
16


                    JEN KELLER


F


50:18
50:45


                            COLUMBIA TEAM D



132
18


                    GREG LAWRENCE


M


50:19
50:45


                            COLUMBIA TEAM E



133
249


                    DUSTIN WILLIAMS


M
NOT SPECIFIED
OR
50:22
50:43



134
265


                    RICHARD DORRANCE


M
PORTLAND
OR
50:24
50:29



135
226


                    VINA HOANG


F
BEAVERTON
OR
50:26
50:39



136
790


                    AUSTIN WIPF


M
PORTLAND
OR
50:29
50:45


                            DTNA3



137
654


                    JEREMY GUTTMAN


M
PORTLAND
OR
50:36
51:01



138
167


                    TERRY C CUTLER


M
BEAVERTON
OR
50:38
51:27



139
355


                    STEPHEN P BRUSS


M
PORTLAND
OR
50:39
52:50



140
592


                    AVIV SHAI


M
PORTLAND
OR
50:40
50:57



141
260


                    AARON P LINDSEY


M
HILLSBORO
OR
50:41
51:17



142
263


                    TIM NGUYEN


M
BEAVERTON
OR
50:43
50:58



143
857


                    ALISON M FRIDAY


F
PORTLAND
OR
50:46
50:57



144
883


                    BRANDON PARSIANI


M
PORTLAND
OR
50:51
50:58



145
620


                    SANGHYUN SEO


M
PORTLAND
OR
51:00
51:41



146
738


                    CORY E WEBER


M
HILLSBORO
OR
51:02
51:25



147
372


                    SRINIDHI N KAUSHIK


M
BEAVERTON
OR
51:05
51:22



148
685


                    ERIC CHEN


M
PORTLAND
OR
51:06
52:06



149
383


                    KEALOHA OYER


M
HILLSBORO
OR
51:08
51:18



150
563


                    CAMERON R WAGNER


M
BEAVERTON
OR
51:08
51:15



151
261


                    JUSTON LI


M
OTHER
OR
51:10
51:44


                            INTEL TEAM D



152
161


                    JAIMIEY I SEARS


M
HILLSBORO
OR
51:12
51:28



153
799


                    MANOJ ATHAWALE


M
HILLSBORO
OR
51:18
52:19



154
277


                    MALLIKARJUNA CHILAKALA


M
HILLSBORO
OR
51:20
51:52


                            INTEL TEAM I



155
368


                    JAYADEV MUNIMALLAPPA


M
PORTLAND
OR
51:22
51:53



156
176


                    ANDREW WENDLANDT


M
HILLSBORO
OR
51:24
52:06



157
422


                    TRISTAN WOEHRLE


M
BEAVERTON
OR
51:34
51:41



158
276


                    PAUL HACK


M
PORTLAND
OR
51:35
52:14



159
595


                    JIANREN TAI


M
PORTLAND
OR
51:38
52:00



160
159


                    EUGENE LUHAVY


M
PORTLAND
OR
51:41
52:31



161
221


                    REET CHATTERJEE


M
BEAVERTON
OR
51:43
52:10



162
4


                    BHASKAR MANDALA


M


51:49
52:10


                            COLUMBIA TEAM A



163
757


                    JOSE MAURICIO MARULANDA


M
HILLSBORO
OR
51:52
52:10



164
571


                    MARC STEVENSON SO


M
BEAVERTON
OR
51:54
52:11



165
805


                    TRISTAN HANSON


M
FOREST GROVE
OR
52:15
52:45



166
398


                    DEREK R COLLIER


M
PORTLAND
OR
52:17
52:41



167
389


                    DANIEL P GARUBBA


M
HILLSBORO
OR
52:25
53:33



168
856


                    AARON J WOODS


M
ALOHA
OR
52:26
52:34



169
748


                    JAMES GREALISH


M
HILLSBORO
OR
52:34
53:18



170
627


                    LUCAS P BEVERLIN


M
HILLSBORO
OR
52:34
52:54



171
885


                    BRIAN HINTZMAN


M
PORTLAND
OR
52:35
52:42



172
542


                    JUSTINE BONNER


F
PORTLAND
OR
52:35
53:09



173
304


                    VANESSA R BRITT


F
PORTLAND
OR
52:36
53:01



174
709


                    RICHMOND B STURGILL


M
TIGARD
OR
52:38
52:55



175
9


                    BETH UNGER


F


52:38
53:08


                            COLUMBIA TEAM C



176
44


                    BINAY SINGH


M
HILLSBORO
OR
52:41
53:04



177
332


                    VASUDEV RUPANAGUNTLA


M
HILLSBORO
OR
52:43
52:51



178
584


                    CODY L COVEY


M
HILLSBORO
OR
52:47
52:52


                            INTEL TEAM F



179
21


                    VINOTHKUMAR RADHAKRISHNAN


M
PORTLAND
OR
52:48
53:02



180
337


                    DEEPAK RAJENDRAKUMARAN


M
HILLSBORO
OR
52:50
53:22



181
459


                    JOHN HAMILTON


M
PORTLAND
OR
52:55
53:24


                            INTEL TEAM K



182
444


                    VARUN K SETLUR


M
HILLSBORO
OR
52:55
53:51



183
211


                    NAHOM YEMANE


M
BEAVERTON
OR
52:58
53:30



184
55


                    ERNIE KHAW


M
HILLSBORO
OR
53:02
53:18



185
613


                    ANTON RODRIGUEZ-DMITRIEV


M
PORTLAND
OR
53:05
54:11



186
129


                    KARL H AMSPACHER


M
HILLSBORO
OR
53:06
53:44



187
599


                    XIAODONG1 YANG


M
PORTLAND
OR
53:09
54:11


                            INTEL TEAM J



188
652


                    CURTIS J HOFFMAN


M
ALOHA
OR
53:12
54:07



189
731


                    ROBERT HEUSSNER


M
PORTLAND
OR
53:16
53:54



190
767


                    ROBERT EHLERT


M
PORTLAND
OR
53:23
53:53



191
170


                    JAYCEE SLACK


F
BEAVERTON
OR
53:26
54:00



192
610


                    YATHIN PISSAY


M
HILLSBORO
OR
53:31
53:52



193
36


                    AJITHPRASADJAIN ADALAGEREJWALANNA


M
BEAVERTON
OR
53:32
53:52



194
707


                    CANDICE L YUCA


F
BEAVERTON
OR
53:33
54:04



195
763


                    THIERRY TAMBE


M
HILLSBORO
OR
53:37
54:15



196
817


                    ERIC GREGORY


M
PORTLAND
OR
53:44
54:45



197
881


                    MICHELLE G DINSMOOR


F
PORTLAND
OR
53:45
53:58



198
280


                    NIKHIL TALPALLIKAR


M
PORTLAND
OR
53:49
54:18


                            INTEL TEAM B



199
760


                    PAUL S MCCARTHY


M
HILLSBORO
OR
53:53
54:52



200
875


                    KRISTINA M HIERSCHE


F
BEAVERTON
OR
53:56
54:15



201
10


                    MIKE HIRT


M


53:58
54:23


                            COLUMBIA TEAM C



202
589


                    BUM SOO KIM


M
NOT SPECIFIED
OR
53:59
54:09



203
780


                    TONY GONZALEZ


M
PORTLAND
OR
53:59
54:55


                            FXG1



204
741


                    BLAKE ADKINS


M
PORTLAND
OR
54:05
55:11



205
69


                    KEATON WEISENBORN


M
PORTLAND
OR
54:09
54:25


                            DTNA1



206
70


                    MAISIE WEISENBORN


F
PORTLAND
OR
54:10
54:25


                            DTNA1



207
48


                    LOUISE R DUNNE


F
PORTLAND
OR
54:16
54:52



208
714


                    CLAYTON A BROWN


M
HILLSBORO
OR
54:17
55:04



209
851


                    HONG NHUNG T TRAN


F
BEAVERTON
OR
54:17
55:06



210
586


                    JOHN S SUMMERS


M
PORTLAND
OR
54:20
55:41



211
289


                    HAREESH KHATTRI


M
NOT SPECIFIED
OR
54:21
54:55



212
664


                    ABHISHEK JAIN


M
HILLSBORO
OR
54:29
55:29



213
386


                    BENJAMIN D MOORE


M
BEAVERTON
OR
54:38
55:11



214
643


                    MEAGEN A GILLISPIE


F
HILLSBORO
OR
54:41
56:05



215
428


                    CHRIS LORD


M
PORTLAND
OR
54:41
56:29



216
242


                    SARAT V DASAKA


M
PORTLAND
OR
54:43
55:22



217
845


                    SUMANT PATANKAR


M
BEAVERTON
OR
54:44
55:17



218
41


                    VIVEK PARANJAPE


M
PORTLAND
OR
54:46
54:58



219
425


                    HOWARD HECK


M
BEAVERTON
OR
54:50
55:08



220
267


                    DANIEL NGUYEN


M
HILLSBORO
OR
54:53
56:05



221
873


                    HAYDEN LOCKHART


M
HILLSBORO
OR
55:00
55:51



222
698


                    JEYASEKAR MARIMUTHU


M
PORTLAND
OR
55:00
55:11



223
802


                    NICK LINDERT


M
PORTLAND
OR
55:00
56:02



224
713


                    RAVI K SARIPALLI


M
PORTLAND
OR
55:00
55:22



225
750


                    RAJKUMAR GOVINDARAJAN


M
HILLSBORO
OR
55:00
55:46



226
35


                    DAMON MAPES


M

In [7]:
all_links = soup.find_all("a")
for link in all_links:
    print(link.get("href"))

mailto:timing@hubertiming.com
https://www.hubertiming.com
/results/2017GPTR
/results/team/2017GPTR
/results/team/2017GPTR10K
/results/summary/2017GPTR10K
None
#tabs-1
https://www.hubertiming.com/
https://facebook.com/hubertiming/
None

In [8]:
# Print the first 10 rows for sanity check
rows = soup.find_all('tr')
print(rows[:10])

[<tr colspan="2">
<b>10K:</b>
</tr>, <tr>
<td>Finishers:</td>
<td>577</td>
</tr>, <tr>
<td>Male:</td>
<td>414</td>
</tr>, <tr>
<td>Female:</td>
<td>163</td>
</tr>, <tr class="header">
<th>Place</th>
<th>Bib</th>
<th>Name</th>
<th>Gender</th>
<th>City</th>
<th>State</th>
<th>Time</th>
<th>Gun Time</th>
<th>Team</th>
</tr>, <tr data-bib="814">
<td>1</td>
<td>814</td>
<td>

                    JARED WILSON

                </td>
<td>M</td>
<td>TIGARD</td>
<td>OR</td>
<td>36:21</td>
<td>36:24</td>
<td></td>
</tr>, <tr data-bib="573">
<td>2</td>
<td>573</td>
<td>

                    NATHAN A SUSTERSIC

                </td>
<td>M</td>
<td>PORTLAND</td>
<td>OR</td>
<td>36:42</td>
<td>36:45</td>
<td>
<img class="lazy teamThumbs" data-src="/teamLogoThumbnail/logo?teamName=INTEL%20TEAM%20F&amp;raceId=1251&amp;state=OR"/>
                            INTEL TEAM F
                        </td>
</tr>, <tr data-bib="687">
<td>3</td>
<td>687</td>
<td>

                    FRANCISCO MAYA

                </td>
<td>M</td>
<td>PORTLAND</td>
<td>OR</td>
<td>37:44</td>
<td>37:48</td>
<td></td>
</tr>, <tr data-bib="623">
<td>4</td>
<td>623</td>
<td>

                    PAUL MORROW

                </td>
<td>M</td>
<td>BEAVERTON</td>
<td>OR</td>
<td>38:34</td>
<td>38:37</td>
<td></td>
</tr>, <tr data-bib="569">
<td>5</td>
<td>569</td>
<td>

                    DEREK G OSBORNE

                </td>
<td>M</td>
<td>HILLSBORO</td>
<td>OR</td>
<td>39:21</td>
<td>39:24</td>
<td>
<img class="lazy teamThumbs" data-src="/teamLogoThumbnail/logo?teamName=INTEL%20TEAM%20F&amp;raceId=1251&amp;state=OR"/>
                            INTEL TEAM F
                        </td>
</tr>]

In [9]:
for row in rows:
    row_td = row.find_all('td')
print(row_td)
type(row_td)

[<td>577</td>, <td>443</td>, <td>

                    LIBBY B MITCHELL

                </td>, <td>F</td>, <td>HILLSBORO</td>, <td>OR</td>, <td>1:41:18</td>, <td>1:42:10</td>, <td></td>]

bs4.element.ResultSet

In [10]:
str_cells = str(row_td)
cleantext = BeautifulSoup(str_cells, "lxml").get_text()
print(cleantext)

[577, 443,

                    LIBBY B MITCHELL

                , F, HILLSBORO, OR, 1:41:18, 1:42:10, ]

In [11]:
import re

list_rows = []
for row in rows:
    cells = row.find_all('td')
    str_cells = str(cells)
    clean = re.compile('<.*?>')
    clean2 = (re.sub(clean, '',str_cells))
    list_rows.append(clean2)
print(clean2)
type(clean2)

[577, 443,

                    LIBBY B MITCHELL

                , F, HILLSBORO, OR, 1:41:18, 1:42:10, ]

str

In [12]:
df = pd.DataFrame(list_rows)
df.head(10)

                                                   0
0                                                 []
1                                  [Finishers:, 577]
2                                       [Male:, 414]
3                                     [Female:, 163]
4                                                 []
5  [1, 814, \r\n\r\n                    JARED WIL...
6  [2, 573, \r\n\r\n                    NATHAN A ...
7  [3, 687, \r\n\r\n                    FRANCISCO...
8  [4, 623, \r\n\r\n                    PAUL MORR...
9  [5, 569, \r\n\r\n                    DEREK G O...

In [13]:
df1 = df[0].str.split(',', expand=True)
df1.head(10)

,0,1,2,3,4,5,6,7,8
0,[],None,None,None,None,None,None,None,None
1,[Finishers:,577],None,None,None,None,None,None,None
2,[Male:,414],None,None,None,None,None,None,None
3,[Female:,163],None,None,None,None,None,None,None
4,[],None,None,None,None,None,None,None,None
5,[1,814,\r\n\r\n JARED WILSON\r\n\...,M,TIGARD,OR,36:21,36:24,]
6,[2,573,\r\n\r\n NATHAN A SUSTERSI...,M,PORTLAND,OR,36:42,36:45,\n\r\n INTEL TEAM ...
7,[3,687,\r\n\r\n FRANCISCO MAYA\r\...,M,PORTLAND,OR,37:44,37:48,]
8,[4,623,\r\n\r\n PAUL MORROW\r\n\r...,M,BEAVERTON,OR,38:34,38:37,]
9,[5,569,\r\n\r\n DEREK G OSBORNE\r...,M,HILLSBORO,OR,39:21,39:24,\n\r\n INTEL TEAM ...

In [14]:
df1[0] = df1[0].str.strip('[')
df1.head(10)

,0,1,2,3,4,5,6,7,8
0,],None,None,None,None,None,None,None,None
1,Finishers:,577],None,None,None,None,None,None,None
2,Male:,414],None,None,None,None,None,None,None
3,Female:,163],None,None,None,None,None,None,None
4,],None,None,None,None,None,None,None,None
5,1,814,\r\n\r\n JARED WILSON\r\n\...,M,TIGARD,OR,36:21,36:24,]
6,2,573,\r\n\r\n NATHAN A SUSTERSI...,M,PORTLAND,OR,36:42,36:45,\n\r\n INTEL TEAM ...
7,3,687,\r\n\r\n FRANCISCO MAYA\r\...,M,PORTLAND,OR,37:44,37:48,]
8,4,623,\r\n\r\n PAUL MORROW\r\n\r...,M,BEAVERTON,OR,38:34,38:37,]
9,5,569,\r\n\r\n DEREK G OSBORNE\r...,M,HILLSBORO,OR,39:21,39:24,\n\r\n INTEL TEAM ...

In [16]:
col_labels = soup.find_all('th')

In [17]:
all_header = []
col_str = str(col_labels)
cleantext2 = BeautifulSoup(col_str, "lxml").get_text()
all_header.append(cleantext2)
print(all_header)

['[Place, Bib, Name, Gender, City, State, Time, Gun Time, Team]']

In [18]:
df2 = pd.DataFrame(all_header)
df2.head()

                                                   0
0  [Place, Bib, Name, Gender, City, State, Time, ...

In [19]:
df3 = df2[0].str.split(',', expand=True)
df3.head()

        0     1      2        3      4       5      6          7       8
0  [Place   Bib   Name   Gender   City   State   Time   Gun Time   Team]

In [20]:
frames = [df3, df1]

df4 = pd.concat(frames)
df4.head(10)

,0,1,2,3,4,5,6,7,8
0,[Place,Bib,Name,Gender,City,State,Time,Gun Time,Team]
0,],None,None,None,None,None,None,None,None
1,Finishers:,577],None,None,None,None,None,None,None
2,Male:,414],None,None,None,None,None,None,None
3,Female:,163],None,None,None,None,None,None,None
4,],None,None,None,None,None,None,None,None
5,1,814,\r\n\r\n JARED WILSON\r\n\...,M,TIGARD,OR,36:21,36:24,]
6,2,573,\r\n\r\n NATHAN A SUSTERSI...,M,PORTLAND,OR,36:42,36:45,\n\r\n INTEL TEAM ...
7,3,687,\r\n\r\n FRANCISCO MAYA\r\...,M,PORTLAND,OR,37:44,37:48,]
8,4,623,\r\n\r\n PAUL MORROW\r\n\r...,M,BEAVERTON,OR,38:34,38:37,]

In [21]:
df5 = df4.rename(columns=df4.iloc[0])
df5.head()

       [Place    Bib   Name   Gender   City   State   Time   Gun Time   Team]
0      [Place    Bib   Name   Gender   City   State   Time   Gun Time   Team]
0           ]   None   None     None   None    None   None       None    None
1  Finishers:   577]   None     None   None    None   None       None    None
2       Male:   414]   None     None   None    None   None       None    None
3     Female:   163]   None     None   None    None   None       None    None

In [22]:
df5.info()
df5.shape

<class 'pandas.core.frame.DataFrame'>
Int64Index: 583 entries, 0 to 581
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   [Place     583 non-null    object
 1    Bib       581 non-null    object
 2    Name      578 non-null    object
 3    Gender    578 non-null    object
 4    City      578 non-null    object
 5    State     578 non-null    object
 6    Time      578 non-null    object
 7    Gun Time  578 non-null    object
 8    Team]     578 non-null    object
dtypes: object(9)
memory usage: 45.5+ KB

(583, 9)

In [23]:
df6 = df5.dropna(axis=0, how='any')

In [24]:
df7 = df6.drop(df6.index[0])
df7.head()

,[Place,Bib,Name,Gender,City,State,Time,Gun Time,Team]
5,1,814,\r\n\r\n JARED WILSON\r\n\...,M,TIGARD,OR,36:21,36:24,]
6,2,573,\r\n\r\n NATHAN A SUSTERSI...,M,PORTLAND,OR,36:42,36:45,\n\r\n INTEL TEAM ...
7,3,687,\r\n\r\n FRANCISCO MAYA\r\...,M,PORTLAND,OR,37:44,37:48,]
8,4,623,\r\n\r\n PAUL MORROW\r\n\r...,M,BEAVERTON,OR,38:34,38:37,]
9,5,569,\r\n\r\n DEREK G OSBORNE\r...,M,HILLSBORO,OR,39:21,39:24,\n\r\n INTEL TEAM ...

In [25]:
df7.rename(columns={'[Place': 'Place'},inplace=True)
df7.rename(columns={' Team]': 'Team'},inplace=True)
df7.head()

,Place,Bib,Name,Gender,City,State,Time,Gun Time,Team
5,1,814,\r\n\r\n JARED WILSON\r\n\...,M,TIGARD,OR,36:21,36:24,]
6,2,573,\r\n\r\n NATHAN A SUSTERSI...,M,PORTLAND,OR,36:42,36:45,\n\r\n INTEL TEAM ...
7,3,687,\r\n\r\n FRANCISCO MAYA\r\...,M,PORTLAND,OR,37:44,37:48,]
8,4,623,\r\n\r\n PAUL MORROW\r\n\r...,M,BEAVERTON,OR,38:34,38:37,]
9,5,569,\r\n\r\n DEREK G OSBORNE\r...,M,HILLSBORO,OR,39:21,39:24,\n\r\n INTEL TEAM ...

In [26]:
df7['Team'] = df7['Team'].str.strip(']')
df7.head()

,Place,Bib,Name,Gender,City,State,Time,Gun Time,Team
5,1,814,\r\n\r\n JARED WILSON\r\n\...,M,TIGARD,OR,36:21,36:24,
6,2,573,\r\n\r\n NATHAN A SUSTERSI...,M,PORTLAND,OR,36:42,36:45,\n\r\n INTEL TEAM ...
7,3,687,\r\n\r\n FRANCISCO MAYA\r\...,M,PORTLAND,OR,37:44,37:48,
8,4,623,\r\n\r\n PAUL MORROW\r\n\r...,M,BEAVERTON,OR,38:34,38:37,
9,5,569,\r\n\r\n DEREK G OSBORNE\r...,M,HILLSBORO,OR,39:21,39:24,\n\r\n INTEL TEAM ...

In [29]:
df7['Team'] = df7['Team'].str.strip('\r\n\r\n')
df7.head()

,Place,Bib,Name,Gender,City,State,Time,Gun Time,Team
5,1,814,\r\n\r\n JARED WILSON\r\n\...,M,TIGARD,OR,36:21,36:24,
6,2,573,\r\n\r\n NATHAN A SUSTERSI...,M,PORTLAND,OR,36:42,36:45,\n\r\n INTEL TEAM ...
7,3,687,\r\n\r\n FRANCISCO MAYA\r\...,M,PORTLAND,OR,37:44,37:48,
8,4,623,\r\n\r\n PAUL MORROW\r\n\r...,M,BEAVERTON,OR,38:34,38:37,
9,5,569,\r\n\r\n DEREK G OSBORNE\r...,M,HILLSBORO,OR,39:21,39:24,\n\r\n INTEL TEAM ...